### ISSUE TITLE
no neighborhoods were significant at FDR < 0.05

### ISSUE THREAD

**Issue by FADHLyemen** [yakirr/cna#2]
Hi, I run cna in my analysis, however I did not get the plot from the res object probably none was found as I got

`"no neighborhoods were significant at FDR < 0.05"`

so how to plot them in gray instead of having empty plot
![image](https://user-images.githubusercontent.com/23288387/119723786-da50ac00-be3b-11eb-9a2a-aff25c3a8024.png)

**Comment by yakirr** [comment]
Dear Fadhl, apologies for the delay! We've now modified the plotting function to still plot the gray UMAP with no overlay if nothing passes the specified FDR threshold. Hope this helps.
